name: Java CI wth maven

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build:
      runs-on:  self-hosted
      steps:
        - name: checkout the code
          uses: actions/checkout@v2
        -  name: Build with the Maven wrapper
           run:  mvn clean install
    test:
      runs-on:  self-hosted
      needs: build      
      steps:
        - name: checkout the code
          uses: actions/checkout@v2

        -  name: Test with the Maven
           run:  mvn test
           
           
